[k8s]
kube-master-01 ansible_host=192.168.11.134
kube-worker-01 ansible_host=192.168.11.135
kube-worker-02 ansible_host=192.168.11.136

[k8s_worker]
kube-worker-01
kube-worker-02

[k8s_master]
kube-master-01

[el9]
kube-master-01
kube-worker-01
kube-worker-02

[all:vars]
ansible_user=ansible
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
